---
title: "Roche Farma - Estudios Pivotales"
author: "Desarrollador: Enrique Mendoza Tincopa"
date: "24 de marzo de 2019"
output:
  html_document:
    theme: united
    highlight: espresso
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
library(tidyverse)
library(readr)
library(readxl)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(forcats)
library(ggExtra)
library(lubridate)
library(DT)
library(shiny)
library(knitr)
library(kableExtra)

# Loading the Papers Dataset

matriz<- read_excel("Matriz_de_papers_actualizado.xlsx", sheet=1)
```

A continuacion una tabla con los estudios clinicos pivotales de algunos de los medicamentos elaborados por Roche. Se puede acceder a cada articulo por medio de los links mencionados, tanto al repositorio en PUBMED como tambien al Journal donde se ha publicado.

```{r cleaning_data, warning=F, echo=F, message=F}
matriz$PUBMED_Link <-paste0("<a href='",matriz$PUBMED_Link,"'></a>")

datatable(matriz,
    filter="top",
    escape = FALSE,
    editable = TRUE, 
    class = 'cell-border stripe',
    extensions = list("Buttons" = NULL,
                      "ColReorder" = NULL,
                      'KeyTable'=NULL),
    options = list(
    pageLenght = 10,
    autoWidth= TRUE,
    dom = "Bfrtip", "t",
    buttons = list('copy','print', I("colvis"), list(extend = "collection", 
                                        buttons = c('csv', 'excel', 'pdf'),
                                        text = "Download")), 
    
    colReorder = TRUE,
    keys = TRUE), 
    caption = htmltools::tags$caption(style="caption-side:bottom; text-align:center;", "Tabla:", htmltools::em("Matriz de Papers Pivotales de Roche Farma (Peru). No todos los articulos listados en la siguiente tabla son Open Source.") 
))


colnames(matriz) <- make.names(colnames(matriz))

matriz$PUBMED_Link <- gsub("\\$", "", matriz$PUBMED_Link)
matriz$PUBMED_Link <- gsub(",", "", matriz$PUBMED_Link)
matriz$PUBMED_Link <- as.character(matriz$PUBMED_Link)
matriz$Journal <- gsub("\\$", "", matriz$Journal)
matriz$Journal <- gsub(",", "", matriz$Journal)
matriz$Journal <- as.character(matriz$Journal)
matriz$Journal_Link<- gsub("\\$", "", matriz$Journal_Link)
matriz$Journal_Link <- gsub(",", "", matriz$Journal_Link)
matriz$Journal_Link <- as.character(matriz$Journal_Link)
matriz$DOI<- gsub("\\$", "", matriz$DOI)
matriz$DOI <- gsub(",", "", matriz$DOI)
matriz$DOI<- as.character(matriz$DOI)
matriz$Condicion <- gsub("\\$", "", matriz$Condicion)
matriz$Condicion <- gsub(",", "", matriz$Condicion)
matriz$Condicion <- as.character(matriz$Condicion)
matriz$Titulo<- gsub("\\$", "", matriz$Titulo)
matriz$Titulo<- gsub(",", "", matriz$Titulo)
matriz$Titulo <- as.character(matriz$Titulo)
matriz$Farmaco_N_C <- gsub("\\$", "", matriz$Farmaco_N_C)
matriz$Farmaco_N_C <- gsub(",", "", matriz$Farmaco_N_C)
matriz$Farmaco_N_C <- as.character(matriz$Farmaco_N_C)
matriz$Farmaco_N_Q <- gsub("\\$", "", matriz$Farmaco_N_Q)
matriz$Farmaco_N_Q <- gsub(",", "", matriz$Farmaco_N_Q)
matriz$Farmaco_N_Q <- as.character(matriz$Farmaco_N_Q)
matriz$Indicacion <- gsub("\\$", "", matriz$Indicacion)
matriz$Indicacion<- gsub(",", "", matriz$Indicacion)
matriz$Indicacion <- as.character(matriz$Indicacion)
```



